services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=shaneelkumar
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data
volumes:
  pgdata:
